Adding Rectangle (4:3) for cropping
benedom/SwiftyCrop pull request #17
Opened 2024-08-14 10:04 UTC by Festanny

Added a new Rectangle shape with a resolution of 4:3

2024-08-14 11:06 UTC, benedom requested changes

2024-08-14 11:06 UTC, benedom commented on Sources/SwiftyCrop/Models/CropViewModel.swift
> +    func calculateDragGestureMaxRectangle() -> CGPoint {
Suggestion: Make this func private and use it in the above func `calculateDragGestureMax`. In the `CropViewModel` you should have access to the `maskShape`. Decide inside the func `calculateDragGestureMax` how to calculate based on the `maskShape`.

This also makes it easier below (I added a comment)

2024-08-14 11:06 UTC, benedom commented on Sources/SwiftyCrop/View/CropView.swift
> +                let maxOffsetPoint = maskShape == .rectangle ? viewModel.calculateDragGestureMaxRectangle() : viewModel.calculateDragGestureMax()
(here)

If the func handles the mask shape you do not need to use a tenary here, makes it less complex and keeps logic inside the viewModel

2024-08-15 09:39 UTC, benedom commented
@Festanny I reworked the cropping functionality for rectangles, adding a more robust way and also making the aspect ratio configurable. Please review and test if this matches your requirements ☺️

2024-08-15 09:55 UTC, benedom approved these changes

2024-08-16 11:36 UTC, Festanny commented
Yes, it fits, everything is cool!

2024-08-16 11:51 UTC, merged